"""
Input validation utilities.
"""
import re
from pathlib import Path
from typing import Optional


def validate_document_id(document_id: str) -> bool:
    """
    Validate a document ID format.

    Document IDs are UUID-like strings generated by uuid.uuid4().
    They should be at least 8 characters and contain only alphanumeric
    characters and hyphens.

    Args:
        document_id: The document ID to validate

    Returns:
        True if valid, False otherwise
    """
    if not document_id:
        return False
    if len(document_id) < 8:
        return False
    if len(document_id) > 64:
        return False
    # Allow alphanumeric, hyphens, and underscores
    pattern = r'^[a-zA-Z0-9_-]+$'
    return bool(re.match(pattern, document_id))


def validate_filename(filename: str) -> bool:
    """
    Validate a filename for security (no path traversal).

    Args:
        filename: The filename to validate

    Returns:
        True if valid, False otherwise
    """
    if not filename:
        return False

    # Check for path traversal attempts
    dangerous_patterns = ['..', '~', '$', '|', '&', ';', '`', '\\']
    for pattern in dangerous_patterns:
        if pattern in filename:
            return False

    # Check filename length
    if len(filename) > 255:
        return False

    # Ensure filename has extension
    path = Path(filename)
    if not path.suffix:
        return False

    return True


def sanitize_filename(filename: str) -> str:
    """
    Sanitize a filename by removing dangerous characters.

    Args:
        filename: The filename to sanitize

    Returns:
        Sanitized filename
    """
    # Remove any path components
    filename = Path(filename).name

    # Replace dangerous characters with underscores
    dangerous_chars = r'[<>:"|?*\x00-\x1f]'
    filename = re.sub(dangerous_chars, '_', filename)

    # Limit length
    if len(filename) > 200:
        name_part = Path(filename).stem[:190]
        ext_part = Path(filename).suffix
        filename = name_part + ext_part

    return filename


def validate_query(query: str, min_length: int = 1, max_length: int = 4000) -> bool:
    """
    Validate a search query.

    Args:
        query: The query to validate
        min_length: Minimum allowed length
        max_length: Maximum allowed length

    Returns:
        True if valid, False otherwise
    """
    if not query:
        return False
    if not isinstance(query, str):
        return False
    stripped = query.strip()
    if len(stripped) < min_length:
        return False
    if len(stripped) > max_length:
        return False
    return True


def validate_pagination(limit: int, offset: int, max_limit: int = 500) -> tuple[int, int]:
    """
    Validate and normalize pagination parameters.

    Args:
        limit: Requested page size
        offset: Number of items to skip
        max_limit: Maximum allowed page size

    Returns:
        Tuple of (normalized_limit, normalized_offset)

    Raises:
        ValueError: If parameters are invalid
    """
    if limit < 1:
        limit = 20
    if limit > max_limit:
        limit = max_limit
    if offset < 0:
        offset = 0

    return limit, offset
